package br.com.guardiao.guardiao.model;

public enum TipoAcao {
    LOGIN_SUCESSO,
    LOGIN_FALHA,

    CRIACAO_ITEM,
    EDICAO_ITEM,
    EXCLUSAO_ITEM,
    RESTAURACAO_ITEM,
    REATIVACAO_ITEM,
    TRANSFERENCIA_ITEM,
    DEVOLUCAO_ITEM,
    IMPORTACAO_XML_ITEM,
    EDICAO_EM_MASSA_ITEM,
    EXCLUSAO_EM_MASSA_ITEM,
    RESTAURACAO_EM_MASSA_ITEM,
    TRANSFERENCIA_EM_MASSA_ITEM,

    CRIACAO_USUARIO,
    EDICAO_USUARIO,
    EXCLUSAO_USUARIO,
    RESET_SENHA_USUARIO,
    ALTERACAO_SENHA_USUARIO,
    ALTERACAO_PERFIL_USUARIO,

    SISTEMA_ROTINA,
    BLOQUEIO_TEMPORARIO_USUARIO;
}